name: Renode Automated Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    # Clone repo with its submodules
    - uses: actions/checkout@v2
      with:
        submodules: true

    # Install python
    - name: Set up Python
      uses: actions/setup-python@v2

    # Install PlatformIO
    - name: Set up platformio
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    # Buil the firmware
    - name: Build Firmware
      run: pio run

    # Upload the generated firmware as an artifact
    - name: Upload ELF
      uses: actions/upload-artifact@v2
      with:
        name: firmware.elf
        path: .pio/build/disco_f407vg/firmware.elf

    # Run renode test inside docker
    - name: Renode Tests
      run: scripts/docker-test.sh

    # Upload the generated test results as an artifact
    - name: Upload Output Dir
      uses: actions/upload-artifact@v2
      with:
        name: Renode Test Results
        path: test_results/